CREATE TABLE lists (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    url_path TEXT NOT NULL,
    name TEXT NOT NULL,
    item_order int[] DEFAULT '{}'
);

CREATE UNIQUE INDEX url_path_index
ON lists (url_path);