CREATE TYPE status_options AS ENUM ('todo', 'doing', 'done');

CREATE TABLE items (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  list_id  INTEGER NOT NULL, 
  name TEXT NOT NULL,
  assign TEXT,
  status status_options DEFAULT 'todo' NOT NULL,
  notes TEXT,
  FOREIGN KEY(list_id) REFERENCES lists(id)
);

